version: '3.7'
services:
  golang:
    container_name: acme_go
    build:
      context: ./docker/golang
      target: develop
    volumes:
      - '.:/go/todo'
    working_dir: '/go/todo'
    command: ['/bin/sh', '-c', 'tail -f /dev/null']
    restart: always
    env_file: .env
    ports:
      - ${WEB_IP}:${WEB_HTTP_PORT}:8080
    links:
      - postgres
  postgres:
    container_name: acme_postgres
    image: postgres:12
    volumes:
      - ./docker/postgres/postgresql.conf:/tmp/postgresql.conf
      - ./docker/postgres/adding_self_signed_cert.sh:/docker-entrypoint-initdb.d/adding_self_signed_cert.sh
    env_file: .env
    ports:
      - 5432:5432
    restart: always
  migrate:
    container_name: od_content_migrate
    image: migrate/migrate
    volumes:
      - './:/migrations'
    working_dir: '/migrations'